# Generated by Django 4.1.7 on 2023-11-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
