# Generated by Django 4.1.7 on 2023-11-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_goal_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='icon',
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default='fa', max_length=50, null=True),
        ),
    ]
