# Generated by Django 4.1.7 on 2023-11-11 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_remove_habit_icon_category_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='habit',
        ),
        migrations.RemoveField(
            model_name='habitevent',
            name='completed',
        ),
        migrations.AddField(
            model_name='goal',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habit',
            name='goal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.goal'),
        ),
        migrations.AddField(
            model_name='habit',
            name='is_positive',
            field=models.BooleanField(default=True),
        ),
    ]
