# Generated by Django 4.1.7 on 2023-11-11 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_remove_goal_habit_remove_habitevent_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='goal',
        ),
        migrations.AddField(
            model_name='goal',
            name='habit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goal', to='habits.habit'),
        ),
    ]
