# Generated by Django 4.1.7 on 2023-11-12 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_remove_habit_goal_goal_habit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goal',
        ),
    ]
