# Generated by Django 4.1.7 on 2023-11-17 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_delete_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='habitevent',
            name='value',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default='fa-solid fa-', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='HabitGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('target', models.PositiveIntegerField()),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('habit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='habits.habit')),
            ],
        ),
    ]
