# Generated by Django 4.1.7 on 2023-11-19 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_habit_description_habitevent_value_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HabitGoal',
        ),
    ]
