# Generated by Django 4.1.7 on 2023-11-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0008_delete_habitgoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitevent',
            name='value_type',
            field=models.CharField(choices=[('minutes', 'minutes'), ('repetition', 'repetition')], default='minutes', max_length=10),
        ),
    ]
