# Generated by Django 4.1.7 on 2023-11-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0009_habitevent_value_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitevent',
            name='value_type',
            field=models.CharField(choices=[('minutes', 'minutes'), ('repetition', 'repetition'), ('quantity', 'quantity')], max_length=10),
        ),
    ]
