# Generated by Django 5.0 on 2023-12-28 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0010_alter_habitevent_value_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='is_positive',
        ),
        migrations.RemoveField(
            model_name='habitevent',
            name='location',
        ),
        migrations.RemoveField(
            model_name='habitevent',
            name='value',
        ),
        migrations.RemoveField(
            model_name='habitevent',
            name='value_type',
        ),
    ]
